name: Deploy Storybook

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Job 1: Deploy ke Chromatic
  chromatic-deployment:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for Chromatic

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Check Chromatic token
        run: |
          if [ -z "${{ secrets.CHROMATIC_PROJECT_TOKEN }}" ]; then
            echo "❌ CHROMATIC_PROJECT_TOKEN is not set!"
            echo "Please add your Chromatic project token to GitHub Secrets:"
            echo "1. Go to https://github.com/${{ github.repository }}/settings/secrets/actions"
            echo "2. Add CHROMATIC_PROJECT_TOKEN with your token from https://www.chromatic.com/"
            exit 1
          fi
          echo "✅ Chromatic token is configured"

      - name: Deploy to Chromatic
        run: npm run chromatic:ci
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

  # Job 2: Deploy ke GitHub Pages (opsional)
  github-pages:
    runs-on: ubuntu-latest
    needs: chromatic-deployment
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Build Storybook
        run: npm run build-storybook

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./storybook-static

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          timeout: 600000

  # Job 3: Visual Testing untuk PR
  visual-tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Run Chromatic for PR
        run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --exit-zero-on-changes
